# A generic, single database configuration for Alembic

[alembic]
# path to migration script directory
script_location = alembic

# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as well as the filename.
# string value, for example 'UTC', 'US/Eastern', etc.
timezone = UTC

# max length of characters which are used to render the slug of script.
max_slug_length = 40

# set to 'true' to run the environment during the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without a corresponding .py file to be detected
# sourceless = false

# version location specification; this defaults to alembic/versions.
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# set to 'true' to search source tree recursively for versions
# recursive_version_locations = false

# output encoding used when printing revision files
# output_encoding = utf-8

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.

[logging]
default_level = INFO
