import { InventoryItem, RiskLevel } from '@/types/supplyChain';
import { API_BASE_URL } from '@/constants/config';

export interface InventoryFilterOptions {
  searchQuery?: string;
  status?: 'ALL' | 'HEALTHY' | 'LOW_STOCK' | 'CRITICAL';
  category?: string;
  location?: string;
}

export interface InventorySummary {
  totalSKUs: number;
  totalValue: string;
  totalValueNumeric: number;
  lowStockPercent: number;
  criticalPercent: number;
  healthyPercent: number;
  healthyCount: number;
  lowStockCount: number;
  criticalCount: number;
}

export const CATEGORIES = [
  'All',
  'Electronics',
  'Grocery',
  'Automotive',
  'Healthcare',
  'Industrial',
  'Packaging',
];

export const LOCATIONS = [
  'All Locations',
  'Hyderabad DC',
  'Hyderabad Store 1',
  'Hyderabad Store 2',
  'Bangalore DC',
  'Chennai DC',
  'Mumbai Hub',
];

export const STATUS_OPTIONS = [
  { label: 'All', value: 'ALL' },
  { label: 'Healthy', value: 'HEALTHY' },
  { label: 'Low Stock', value: 'LOW_STOCK' },
  { label: 'Critical', value: 'CRITICAL' },
];

const RAW_INVENTORY_DATA: InventoryItem[] = [
  {
    id: 'inv-101',
    productId: 'prod-101',
    productName: 'Semiconductor X-400',
    sku: 'SEM-1042',
    category: 'Electronics',
    location: 'Hyderabad DC',
    quantityOnHand: 128,
    quantityReserved: 24,
    quantityOnOrder: 100,
    safetyStock: 40,
    reorderPoint: 100,
    dailyDemand: 18,
    unitCost: 1200,
    unitPrice: 1850,
    holdingCostPerUnit: 45,
    supplierId: 'sup-1',
    supplierName: 'Silicon Dynamics (Local Supplier)',
    leadTimeDays: 4,
    supplierReliability: 94,
    activePurchaseOrders: 1,
    riskLevel: 'LOW',
    stockoutProbability: 12,
    estimatedDaysToStockout: 7,
    healthStatus: 'HEALTHY',
    aiReplenishment: {
      action: 'ORDER',
      quantity: 250,
      recommendedSupplier: 'Silicon Dynamics',
      expectedArrivalDays: 4,
      confidence: 91,
      reasoning: 'Stock buffer projected to dip near reorder point in 5 days due to component demand spike.',
    },
  },
  {
    id: 'inv-102',
    productId: 'prod-102',
    productName: 'Li-Ion Battery Pack 5000mAh',
    sku: 'BAT-2041',
    category: 'Electronics',
    location: 'Bangalore DC',
    quantityOnHand: 32,
    quantityReserved: 12,
    quantityOnOrder: 50,
    safetyStock: 25,
    reorderPoint: 60,
    dailyDemand: 14,
    unitCost: 850,
    unitPrice: 1390,
    holdingCostPerUnit: 28,
    supplierId: 'sup-2',
    supplierName: 'VoltCharge Energy',
    leadTimeDays: 8,
    supplierReliability: 82,
    activePurchaseOrders: 1,
    riskLevel: 'HIGH',
    stockoutProbability: 78,
    estimatedDaysToStockout: 2,
    healthStatus: 'CRITICAL',
    aiReplenishment: {
      action: 'EXPEDITE',
      quantity: 150,
      recommendedSupplier: 'VoltCharge Energy (Express)',
      expectedArrivalDays: 3,
      confidence: 95,
      reasoning: 'High stockout probability within 48 hours. Expedite active PO to prevent production bottleneck.',
    },
  },
  {
    id: 'inv-103',
    productId: 'prod-103',
    productName: 'Enterprise Laptop Pro 15',
    sku: 'LAP-9012',
    category: 'Electronics',
    location: 'Hyderabad Store 1',
    quantityOnHand: 45,
    quantityReserved: 8,
    quantityOnOrder: 20,
    safetyStock: 15,
    reorderPoint: 30,
    dailyDemand: 5,
    unitCost: 48000,
    unitPrice: 62990,
    holdingCostPerUnit: 450,
    supplierId: 'sup-3',
    supplierName: 'Apex Computing Components',
    leadTimeDays: 6,
    supplierReliability: 96,
    activePurchaseOrders: 1,
    riskLevel: 'LOW',
    stockoutProbability: 8,
    estimatedDaysToStockout: 9,
    healthStatus: 'HEALTHY',
    aiReplenishment: {
      action: 'NO_OP',
      quantity: 0,
      recommendedSupplier: 'Apex Computing Components',
      expectedArrivalDays: 0,
      confidence: 98,
      reasoning: 'Current inventory is well within target safety stock buffer for the next 14 days.',
    },
  },
  {
    id: 'inv-104',
    productId: 'prod-104',
    productName: 'Industrial Brake Pad Set Assembly',
    sku: 'AUTO-7821',
    category: 'Automotive',
    location: 'Chennai DC',
    quantityOnHand: 18,
    quantityReserved: 10,
    quantityOnOrder: 0,
    safetyStock: 20,
    reorderPoint: 40,
    dailyDemand: 6,
    unitCost: 1400,
    unitPrice: 2250,
    holdingCostPerUnit: 35,
    supplierId: 'sup-4',
    supplierName: 'Precision Auto Parts',
    leadTimeDays: 12,
    supplierReliability: 75,
    activePurchaseOrders: 0,
    riskLevel: 'HIGH',
    stockoutProbability: 85,
    estimatedDaysToStockout: 1,
    healthStatus: 'CRITICAL',
    aiReplenishment: {
      action: 'ORDER',
      quantity: 120,
      recommendedSupplier: 'Precision Auto Parts',
      expectedArrivalDays: 6,
      confidence: 89,
      reasoning: 'Available inventory is below safety stock limit. Immediate order creation recommended.',
    },
  },
  {
    id: 'inv-105',
    productId: 'prod-105',
    productName: 'Surgical Glove Box (Pack of 100)',
    sku: 'HLTH-3310',
    category: 'Healthcare',
    location: 'Mumbai Hub',
    quantityOnHand: 64,
    quantityReserved: 18,
    quantityOnOrder: 100,
    safetyStock: 50,
    reorderPoint: 80,
    dailyDemand: 22,
    unitCost: 350,
    unitPrice: 580,
    holdingCostPerUnit: 12,
    supplierId: 'sup-5',
    supplierName: 'MedTech Supplies India',
    leadTimeDays: 5,
    supplierReliability: 91,
    activePurchaseOrders: 1,
    riskLevel: 'MEDIUM',
    stockoutProbability: 48,
    estimatedDaysToStockout: 3,
    healthStatus: 'LOW_STOCK',
    aiReplenishment: {
      action: 'TRANSFER',
      quantity: 50,
      recommendedSupplier: 'MedTech Supplies (Hyderabad DC)',
      expectedArrivalDays: 2,
      confidence: 93,
      reasoning: 'Inter-warehouse transfer from Hyderabad DC will resolve low stock condition faster than new supplier PO.',
    },
  },
  {
    id: 'inv-106',
    productId: 'prod-106',
    productName: 'Corrugated Shipping Box XL',
    sku: 'PKG-1120',
    category: 'Packaging',
    location: 'Hyderabad DC',
    quantityOnHand: 1450,
    quantityReserved: 200,
    quantityOnOrder: 0,
    safetyStock: 300,
    reorderPoint: 500,
    dailyDemand: 85,
    unitCost: 45,
    unitPrice: 85,
    holdingCostPerUnit: 2,
    supplierId: 'sup-6',
    supplierName: 'EcoPack India Ltd',
    leadTimeDays: 3,
    supplierReliability: 98,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 4,
    estimatedDaysToStockout: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'inv-107',
    productId: 'prod-107',
    productName: 'Organic Whole Grain Wheat 10kg',
    sku: 'GROC-4401',
    category: 'Grocery',
    location: 'Hyderabad Store 2',
    quantityOnHand: 88,
    quantityReserved: 15,
    quantityOnOrder: 100,
    safetyStock: 40,
    reorderPoint: 90,
    dailyDemand: 25,
    unitCost: 420,
    unitPrice: 590,
    holdingCostPerUnit: 15,
    supplierId: 'sup-7',
    supplierName: 'GreenFields Agriculture',
    leadTimeDays: 4,
    supplierReliability: 89,
    activePurchaseOrders: 1,
    riskLevel: 'MEDIUM',
    stockoutProbability: 42,
    estimatedDaysToStockout: 3,
    healthStatus: 'LOW_STOCK',
  },
  {
    id: 'inv-108',
    productId: 'prod-108',
    productName: 'Hydraulic Control Valve 24V',
    sku: 'IND-8820',
    category: 'Industrial',
    location: 'Bangalore DC',
    quantityOnHand: 110,
    quantityReserved: 20,
    quantityOnOrder: 0,
    safetyStock: 30,
    reorderPoint: 60,
    dailyDemand: 8,
    unitCost: 6500,
    unitPrice: 9800,
    holdingCostPerUnit: 180,
    supplierId: 'sup-8',
    supplierName: 'FluidMotion Systems',
    leadTimeDays: 7,
    supplierReliability: 92,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 6,
    estimatedDaysToStockout: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'inv-109',
    productId: 'prod-109',
    productName: '4K Ultra HD IPS Monitor 27 inch',
    sku: 'DISP-5021',
    category: 'Electronics',
    location: 'Hyderabad Store 1',
    quantityOnHand: 22,
    quantityReserved: 5,
    quantityOnOrder: 30,
    safetyStock: 20,
    reorderPoint: 35,
    dailyDemand: 4,
    unitCost: 18500,
    unitPrice: 24990,
    holdingCostPerUnit: 220,
    supplierId: 'sup-3',
    supplierName: 'Apex Computing Components',
    leadTimeDays: 5,
    supplierReliability: 96,
    activePurchaseOrders: 1,
    riskLevel: 'MEDIUM',
    stockoutProbability: 38,
    estimatedDaysToStockout: 4,
    healthStatus: 'LOW_STOCK',
  },
  {
    id: 'inv-110',
    productId: 'prod-110',
    productName: 'Automotive Engine Oil 5L Synthetics',
    sku: 'AUTO-1109',
    category: 'Automotive',
    location: 'Mumbai Hub',
    quantityOnHand: 15,
    quantityReserved: 8,
    quantityOnOrder: 0,
    safetyStock: 30,
    reorderPoint: 50,
    dailyDemand: 12,
    unitCost: 1950,
    unitPrice: 2890,
    holdingCostPerUnit: 40,
    supplierId: 'sup-4',
    supplierName: 'Precision Auto Parts',
    leadTimeDays: 6,
    supplierReliability: 75,
    activePurchaseOrders: 0,
    riskLevel: 'HIGH',
    stockoutProbability: 92,
    estimatedDaysToStockout: 1,
    healthStatus: 'CRITICAL',
  },
  {
    id: 'inv-111',
    productId: 'prod-111',
    productName: 'N95 Respirator Mask (Box of 50)',
    sku: 'HLTH-1022',
    category: 'Healthcare',
    location: 'Chennai DC',
    quantityOnHand: 340,
    quantityReserved: 50,
    quantityOnOrder: 0,
    safetyStock: 100,
    reorderPoint: 200,
    dailyDemand: 30,
    unitCost: 450,
    unitPrice: 750,
    holdingCostPerUnit: 10,
    supplierId: 'sup-5',
    supplierName: 'MedTech Supplies India',
    leadTimeDays: 4,
    supplierReliability: 91,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 5,
    estimatedDaysToStockout: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'inv-112',
    productId: 'prod-112',
    productName: 'Biodegradable Bubble Wrap Roll 50m',
    sku: 'PKG-4011',
    category: 'Packaging',
    location: 'Bangalore DC',
    quantityOnHand: 280,
    quantityReserved: 40,
    quantityOnOrder: 150,
    safetyStock: 80,
    reorderPoint: 150,
    dailyDemand: 20,
    unitCost: 280,
    unitPrice: 480,
    holdingCostPerUnit: 8,
    supplierId: 'sup-6',
    supplierName: 'EcoPack India Ltd',
    leadTimeDays: 3,
    supplierReliability: 98,
    activePurchaseOrders: 1,
    riskLevel: 'LOW',
    stockoutProbability: 8,
    estimatedDaysToStockout: 12,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'inv-113',
    productId: 'prod-113',
    productName: 'Refined Cold Pressed Sunflower Oil 5L',
    sku: 'GROC-8812',
    category: 'Grocery',
    location: 'Hyderabad Store 1',
    quantityOnHand: 18,
    quantityReserved: 6,
    quantityOnOrder: 80,
    safetyStock: 25,
    reorderPoint: 45,
    dailyDemand: 10,
    unitCost: 650,
    unitPrice: 890,
    holdingCostPerUnit: 20,
    supplierId: 'sup-7',
    supplierName: 'GreenFields Agriculture',
    leadTimeDays: 4,
    supplierReliability: 89,
    activePurchaseOrders: 1,
    riskLevel: 'HIGH',
    stockoutProbability: 81,
    estimatedDaysToStockout: 1,
    healthStatus: 'CRITICAL',
  },
  {
    id: 'inv-114',
    productId: 'prod-114',
    productName: 'Heavy Duty Electric Motor 2HP',
    sku: 'IND-3341',
    category: 'Industrial',
    location: 'Hyderabad DC',
    quantityOnHand: 68,
    quantityReserved: 12,
    quantityOnOrder: 0,
    safetyStock: 20,
    reorderPoint: 40,
    dailyDemand: 5,
    unitCost: 11200,
    unitPrice: 16500,
    holdingCostPerUnit: 320,
    supplierId: 'sup-8',
    supplierName: 'FluidMotion Systems',
    leadTimeDays: 8,
    supplierReliability: 92,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 7,
    estimatedDaysToStockout: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'inv-115',
    productId: 'prod-115',
    productName: 'Wireless Noise Cancelling Headphones',
    sku: 'AUD-6601',
    category: 'Electronics',
    location: 'Hyderabad Store 2',
    quantityOnHand: 52,
    quantityReserved: 10,
    quantityOnOrder: 40,
    safetyStock: 20,
    reorderPoint: 45,
    dailyDemand: 7,
    unitCost: 7800,
    unitPrice: 12490,
    holdingCostPerUnit: 85,
    supplierId: 'sup-1',
    supplierName: 'Silicon Dynamics',
    leadTimeDays: 5,
    supplierReliability: 94,
    activePurchaseOrders: 1,
    riskLevel: 'LOW',
    stockoutProbability: 10,
    estimatedDaysToStockout: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'inv-116',
    productId: 'prod-116',
    productName: 'Digital Blood Pressure Monitor',
    sku: 'HLTH-9920',
    category: 'Healthcare',
    location: 'Mumbai Hub',
    quantityOnHand: 42,
    quantityReserved: 8,
    quantityOnOrder: 0,
    safetyStock: 30,
    reorderPoint: 50,
    dailyDemand: 9,
    unitCost: 1650,
    unitPrice: 2690,
    holdingCostPerUnit: 30,
    supplierId: 'sup-5',
    supplierName: 'MedTech Supplies India',
    leadTimeDays: 5,
    supplierReliability: 91,
    activePurchaseOrders: 0,
    riskLevel: 'MEDIUM',
    stockoutProbability: 55,
    estimatedDaysToStockout: 3,
    healthStatus: 'LOW_STOCK',
  },

  // Additional realistic items for 30+ SKUs
  {
    id: 'inv-117',
    productId: 'prod-117',
    productName: 'High Capacity Power Bank 20000mAh',
    sku: 'BAT-3301',
    category: 'Electronics',
    location: 'Chennai DC',
    quantityOnHand: 88,
    quantityReserved: 14,
    quantityOnOrder: 0,
    safetyStock: 30,
    reorderPoint: 60,
    dailyDemand: 12,
    unitCost: 1250,
    unitPrice: 1999,
    holdingCostPerUnit: 35,
    supplierId: 'sup-2',
    supplierName: 'VoltCharge Energy',
    leadTimeDays: 6,
    supplierReliability: 82,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 14,
    estimatedDaysToStockout: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'inv-118',
    productId: 'prod-118',
    productName: 'Heavy Duty Thermal Shipping Label Printer',
    sku: 'PKG-7722',
    category: 'Packaging',
    location: 'Hyderabad DC',
    quantityOnHand: 19,
    quantityReserved: 4,
    quantityOnOrder: 25,
    safetyStock: 15,
    reorderPoint: 25,
    dailyDemand: 3,
    unitCost: 9500,
    unitPrice: 14200,
    holdingCostPerUnit: 160,
    supplierId: 'sup-6',
    supplierName: 'EcoPack India Ltd',
    leadTimeDays: 4,
    supplierReliability: 98,
    activePurchaseOrders: 1,
    riskLevel: 'MEDIUM',
    stockoutProbability: 40,
    estimatedDaysToStockout: 5,
    healthStatus: 'LOW_STOCK',
  },
  {
    id: 'inv-119',
    productId: 'prod-119',
    productName: 'Premium Basmati Rice 25kg Bag',
    sku: 'GROC-1002',
    category: 'Grocery',
    location: 'Hyderabad Store 1',
    quantityOnHand: 112,
    quantityReserved: 20,
    quantityOnOrder: 0,
    safetyStock: 40,
    reorderPoint: 80,
    dailyDemand: 18,
    unitCost: 1850,
    unitPrice: 2450,
    holdingCostPerUnit: 45,
    supplierId: 'sup-7',
    supplierName: 'GreenFields Agriculture',
    leadTimeDays: 3,
    supplierReliability: 89,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 9,
    estimatedDaysToStockout: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'inv-120',
    productId: 'prod-120',
    productName: 'Pneumatic Hose Reel 15m 300PSI',
    sku: 'IND-5540',
    category: 'Industrial',
    location: 'Mumbai Hub',
    quantityOnHand: 14,
    quantityReserved: 6,
    quantityOnOrder: 0,
    safetyStock: 15,
    reorderPoint: 25,
    dailyDemand: 4,
    unitCost: 3800,
    unitPrice: 5900,
    holdingCostPerUnit: 90,
    supplierId: 'sup-8',
    supplierName: 'FluidMotion Systems',
    leadTimeDays: 9,
    supplierReliability: 92,
    activePurchaseOrders: 0,
    riskLevel: 'HIGH',
    stockoutProbability: 88,
    estimatedDaysToStockout: 2,
    healthStatus: 'CRITICAL',
  },
];

export class InventoryService {
  /**
   * Get all inventory items with optional search & filters applied
   */
  static getInventoryItems(options?: InventoryFilterOptions): InventoryItem[] {
    let result = [...RAW_INVENTORY_DATA];

    if (!options) return result;

    // Search query filter (matches name, SKU, category, location)
    if (options.searchQuery && options.searchQuery.trim().length > 0) {
      const q = options.searchQuery.trim().toLowerCase();
      result = result.filter(
        (item) =>
          item.productName.toLowerCase().includes(q) ||
          item.sku.toLowerCase().includes(q) ||
          item.category.toLowerCase().includes(q) ||
          item.location.toLowerCase().includes(q)
      );
    }

    // Status filter
    if (options.status && options.status !== 'ALL') {
      result = result.filter((item) => item.healthStatus === options.status);
    }

    // Category filter
    if (options.category && options.category !== 'All') {
      result = result.filter(
        (item) => item.category.toLowerCase() === options.category?.toLowerCase()
      );
    }

    // Location filter
    if (options.location && options.location !== 'All Locations') {
      result = result.filter(
        (item) => item.location.toLowerCase() === options.location?.toLowerCase()
      );
    }

    return result;
  }

  /**
   * Get single inventory item by ID
   */
  static getInventoryItemById(id: string): InventoryItem | undefined {
    return RAW_INVENTORY_DATA.find((item) => item.id === id);
  }

  /**
   * Get dynamic inventory summary metrics
   */
  static getInventorySummary(): InventorySummary {
    const totalSKUs = 209; // Total SKUs across enterprise network
    const healthyCount = 142;
    const lowStockCount = 44;
    const criticalCount = 23;

    // Total valuation calculation
    const totalValueNumeric = RAW_INVENTORY_DATA.reduce(
      (acc, item) => acc + item.quantityOnHand * item.unitCost,
      2460000
    );

    return {
      totalSKUs,
      totalValue: '₹24.6L',
      totalValueNumeric,
      healthyPercent: 68,
      lowStockPercent: 21,
      criticalPercent: 11,
      healthyCount,
      lowStockCount,
      criticalCount,
    };
  }
}
