import {
  Product,
  InventoryItem,
  Supplier,
  Recommendation,
  SimulationResult,
  Alert,
  ActivityItem,
  KPIMetric,
  DemandInventoryPoint,
  InventoryHealthSummary,
} from '@/types/supplyChain';

export const MOCK_KPI_METRICS: KPIMetric[] = [
  {
    id: 'kpi-1',
    label: 'Total Inventory Value',
    value: '₹24.6L',
    rawNumericValue: 2460000,
    change: '+4.2%',
    isPositiveTrend: true,
    context: 'vs last month',
    icon: 'account-balance-wallet',
  },
  {
    id: 'kpi-2',
    label: 'Service Level',
    value: '94.2%',
    rawNumericValue: 94.2,
    change: '+1.1%',
    isPositiveTrend: true,
    context: 'Target: 95.0%',
    icon: 'verified',
  },
  {
    id: 'kpi-3',
    label: 'Potential Profit',
    value: '₹4.82L',
    rawNumericValue: 482000,
    change: '+₹64K',
    isPositiveTrend: true,
    context: 'Optimization opp.',
    icon: 'trending-up',
  },
  {
    id: 'kpi-4',
    label: 'Supply Chain Risk',
    value: 'Medium',
    rawNumericValue: 2,
    change: '2 Critical',
    isPositiveTrend: false,
    context: 'Action required',
    icon: 'warning',
  },
];

export const MOCK_INVENTORY_HEALTH: InventoryHealthSummary = {
  healthyPercent: 68,
  lowStockPercent: 21,
  criticalPercent: 11,
  healthyCount: 142,
  lowStockCount: 44,
  criticalCount: 23,
  totalProducts: 209,
};

export const MOCK_DEMAND_INVENTORY_CHART: DemandInventoryPoint[] = [
  { day: 'Day 1', demand: 180, availableInventory: 450 },
  { day: 'Day 3', demand: 210, availableInventory: 430 },
  { day: 'Day 5', demand: 195, availableInventory: 410 },
  { day: 'Day 7', demand: 240, availableInventory: 380 },
  { day: 'Day 9', demand: 310, availableInventory: 350 },
  { day: 'Day 11', demand: 280, availableInventory: 320 },
  { day: 'Day 13', demand: 220, availableInventory: 290 },
  { day: 'Day 15', demand: 350, availableInventory: 600 }, // Replenishment arrival
  { day: 'Day 17', demand: 320, availableInventory: 570 },
  { day: 'Day 19', demand: 290, availableInventory: 530 },
  { day: 'Day 21', demand: 330, availableInventory: 490 },
  { day: 'Day 23', demand: 410, availableInventory: 440 },
  { day: 'Day 25', demand: 380, availableInventory: 400 },
  { day: 'Day 27', demand: 360, availableInventory: 360 },
  { day: 'Day 29', demand: 420, availableInventory: 310 },
  { day: 'Day 30', demand: 450, availableInventory: 280 },
];

export const MOCK_RECOMMENDATIONS: Recommendation[] = RecommendationService.getRecommendations();

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alt-001',
    severity: 'CRITICAL',
    title: 'Critical Stockout Risk',
    message: 'Semiconductor X may stock out in 4 days.',
    timestamp: '10 mins ago',
    productId: 'prod-101',
    actionRequired: 'Review Order Recommendation',
  },
  {
    id: 'alt-002',
    severity: 'WARNING',
    title: 'Supplier Lead Time Spike',
    message: 'Overseas supplier lead time increased by 2 days.',
    timestamp: '1 hour ago',
    supplierId: 'sup-501',
    actionRequired: 'Expedite Air Freight',
  },
  {
    id: 'alt-003',
    severity: 'INFO',
    title: 'Logistics Route Notice',
    message: 'Weather disruption detected along Route 3.',
    timestamp: '3 hours ago',
    actionRequired: 'Reroute via Logistics Hub 2',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-101',
    sku: 'SC-X-9900',
    name: 'Semiconductor X',
    category: 'Electronics',
    price: 4500,
    cost: 3100,
    stockLevel: 140,
    reorderPoint: 200,
    leadTimeDays: 4,
    supplierId: 'sup-101',
    supplierName: 'Local Supplier',
    status: 'LOW_STOCK',
  },
  {
    id: 'prod-204',
    sku: 'MC-80-V2',
    name: 'Motor Controller',
    category: 'Hardware',
    price: 8200,
    cost: 5900,
    stockLevel: 45,
    reorderPoint: 100,
    leadTimeDays: 10,
    supplierId: 'sup-202',
    supplierName: 'Precision Motors Tech',
    status: 'CRITICAL',
  },
  {
    id: 'prod-309',
    sku: 'PY-150-GEN',
    name: 'Product Y',
    category: 'Assemblies',
    price: 2400,
    cost: 1600,
    stockLevel: 620,
    reorderPoint: 250,
    leadTimeDays: 7,
    supplierId: 'sup-303',
    supplierName: 'Apex Components',
    status: 'SURPLUS',
  },
  {
    id: 'prod-402',
    sku: 'PS-12V-5A',
    name: 'Power Module 12V',
    category: 'Electronics',
    price: 1850,
    cost: 1100,
    stockLevel: 480,
    reorderPoint: 150,
    leadTimeDays: 5,
    supplierId: 'sup-101',
    supplierName: 'Local Supplier',
    status: 'IN_STOCK',
  },
  {
    id: 'prod-511',
    sku: 'SS-HD-4K',
    name: 'Industrial Sensor Array',
    category: 'Sensors',
    price: 12500,
    cost: 8900,
    stockLevel: 310,
    reorderPoint: 100,
    leadTimeDays: 12,
    supplierId: 'sup-404',
    supplierName: 'OmniSensors Ltd',
    status: 'IN_STOCK',
  },
];

import { SupplierService } from './supplierService';

export const MOCK_SUPPLIERS: Supplier[] = SupplierService.getSuppliers();

import { SimulationService } from './simulationService';

export const MOCK_SIMULATION_RESULTS: SimulationResult[] = [
  {
    id: 'sim-001',
    runId: 'sim-run-demo',
    policyName: 'AI RL-Agent',
    policyType: 'RL_AGENT',
    description: 'Hybrid DQN / CQL Decision Policy',
    durationDays: 30,
    skuCount: 209,
    locationCount: 8,
    serviceLevel: 98.4,
    stockoutRate: 0.8,
    totalHoldingCost: 142000,
    projectedProfit: 524000,
    totalOrders: 28,
    totalTransfers: 16,
    totalExpedites: 4,
    totalDiscounts: 3,
    averageReward: 42.5,
    overallScore: 3580,
    isBestOverall: true,
    runDate: 'Today, 11:20 AM',
  },
  {
    id: 'sim-002',
    runId: 'sim-run-demo',
    policyName: 'Dynamic Heuristic',
    policyType: 'HEURISTIC',
    description: 'Rule-Based Inventory Optimization',
    durationDays: 30,
    skuCount: 209,
    locationCount: 8,
    serviceLevel: 94.1,
    stockoutRate: 3.2,
    totalHoldingCost: 189000,
    projectedProfit: 462000,
    totalOrders: 38,
    totalTransfers: 11,
    totalExpedites: 10,
    totalDiscounts: 6,
    averageReward: 28.2,
    overallScore: 2410,
    isBestOverall: false,
    runDate: 'Yesterday, 04:45 PM',
  },
  {
    id: 'sim-003',
    runId: 'sim-run-demo',
    policyName: 'Manual Ordering',
    policyType: 'MANUAL',
    description: 'Traditional Human Decision Process',
    durationDays: 30,
    skuCount: 209,
    locationCount: 8,
    serviceLevel: 89.5,
    stockoutRate: 7.6,
    totalHoldingCost: 245000,
    projectedProfit: 381000,
    totalOrders: 48,
    totalTransfers: 4,
    totalExpedites: 16,
    totalDiscounts: 2,
    averageReward: 16.4,
    overallScore: 1450,
    isBestOverall: false,
    runDate: '3 days ago',
  },
];

import { ActivityService } from './activityService';

export const MOCK_ACTIVITIES: ActivityItem[] = ActivityService.getActivities();

export const MOCK_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'inv-101',
    productId: 'prod-101',
    productName: 'Semiconductor X',
    sku: 'SEM-1042',
    category: 'Electronics',
    location: 'Warehouse A - Sec 4',
    quantityOnHand: 128,
    quantityReserved: 28,
    quantityOnOrder: 100,
    safetyStock: 80,
    reorderPoint: 150,
    dailyDemand: 42,
    unitCost: 3100,
    unitPrice: 4500,
    holdingCostPerUnit: 120,
    supplierId: 'sup-101',
    supplierName: 'Taiwan Components',
    leadTimeDays: 4,
    supplierReliability: 96,
    activePurchaseOrders: 2,
    riskLevel: 'HIGH',
    stockoutProbability: 78,
    estimatedDaysToStockout: 3,
    healthStatus: 'CRITICAL',
    aiReplenishment: {
      action: 'ORDER',
      quantity: 250,
      recommendedSupplier: 'Taiwan Components',
      expectedArrivalDays: 3,
      confidence: 91,
      reasoning: 'Current inventory is below the reorder point and projected demand indicates a stockout within 4 days.',
    },
    demandTrend: [
      { day: 'Day 1', demand: 38, availableInventory: 240 },
      { day: 'Day 5', demand: 40, availableInventory: 210 },
      { day: 'Day 10', demand: 42, availableInventory: 180 },
      { day: 'Day 15', demand: 45, availableInventory: 155 },
      { day: 'Day 20', demand: 41, availableInventory: 140 },
      { day: 'Day 25', demand: 44, availableInventory: 132 },
      { day: 'Day 30', demand: 42, availableInventory: 100 },
    ],
  },
  {
    id: 'inv-204',
    productId: 'prod-204',
    productName: 'Motor Controller',
    sku: 'MOT-2041',
    category: 'Hardware',
    location: 'Warehouse B - Sec 1',
    quantityOnHand: 420,
    quantityReserved: 40,
    quantityOnOrder: 0,
    safetyStock: 120,
    reorderPoint: 200,
    dailyDemand: 38,
    unitCost: 5900,
    unitPrice: 8200,
    holdingCostPerUnit: 250,
    supplierId: 'sup-202',
    supplierName: 'Global Motors',
    leadTimeDays: 10,
    supplierReliability: 94,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 5,
    estimatedDaysToStockout: 11,
    healthStatus: 'HEALTHY',
    aiReplenishment: {
      action: 'NO_OP',
      quantity: 0,
      recommendedSupplier: 'Global Motors',
      expectedArrivalDays: 10,
      confidence: 95,
      reasoning: 'Stock levels are optimal with sufficient buffer for the next 11 days of demand.',
    },
    demandTrend: [
      { day: 'Day 1', demand: 35, availableInventory: 500 },
      { day: 'Day 5', demand: 37, availableInventory: 480 },
      { day: 'Day 10', demand: 40, availableInventory: 450 },
      { day: 'Day 15', demand: 36, availableInventory: 435 },
      { day: 'Day 20', demand: 38, availableInventory: 420 },
      { day: 'Day 25', demand: 39, availableInventory: 400 },
      { day: 'Day 30', demand: 38, availableInventory: 380 },
    ],
  },
  {
    id: 'inv-402',
    productId: 'prod-402',
    productName: 'Power Module 12V',
    sku: 'PWR-1205',
    category: 'Electronics',
    location: 'Warehouse A - Sec 2',
    quantityOnHand: 85,
    quantityReserved: 15,
    quantityOnOrder: 150,
    safetyStock: 50,
    reorderPoint: 120,
    dailyDemand: 25,
    unitCost: 1100,
    unitPrice: 1850,
    holdingCostPerUnit: 45,
    supplierId: 'sup-101',
    supplierName: 'Local Supplier',
    leadTimeDays: 5,
    supplierReliability: 92,
    activePurchaseOrders: 1,
    riskLevel: 'MEDIUM',
    stockoutProbability: 45,
    estimatedDaysToStockout: 3,
    healthStatus: 'LOW_STOCK',
    aiReplenishment: {
      action: 'EXPEDITE',
      quantity: 150,
      recommendedSupplier: 'Local Supplier',
      expectedArrivalDays: 2,
      confidence: 88,
      reasoning: 'Stock is currently low. Expediting PO #409 will prevent potential stockout during weekend surge.',
    },
    demandTrend: [
      { day: 'Day 1', demand: 22, availableInventory: 160 },
      { day: 'Day 10', demand: 24, availableInventory: 120 },
      { day: 'Day 20', demand: 26, availableInventory: 90 },
      { day: 'Day 30', demand: 25, availableInventory: 70 },
    ],
  },
  {
    id: 'inv-511',
    productId: 'prod-511',
    productName: 'Industrial Sensor Array',
    sku: 'SNS-4000',
    category: 'Sensors',
    location: 'Warehouse C - Sec 5',
    quantityOnHand: 310,
    quantityReserved: 20,
    quantityOnOrder: 0,
    safetyStock: 60,
    reorderPoint: 100,
    dailyDemand: 15,
    unitCost: 8900,
    unitPrice: 12500,
    holdingCostPerUnit: 300,
    supplierId: 'sup-404',
    supplierName: 'OmniSensors Ltd',
    leadTimeDays: 12,
    supplierReliability: 89,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 2,
    estimatedDaysToStockout: 20,
    healthStatus: 'HEALTHY',
    aiReplenishment: {
      action: 'NO_OP',
      quantity: 0,
      recommendedSupplier: 'OmniSensors Ltd',
      expectedArrivalDays: 12,
      confidence: 96,
      reasoning: 'Inventory levels are healthy. No replenishment required for the next 3 weeks.',
    },
  },
  {
    id: 'inv-601',
    productId: 'prod-601',
    productName: 'Lithium Ion Battery Pack 48V',
    sku: 'BAT-4800',
    category: 'Power Units',
    location: 'Warehouse A - Sec 9',
    quantityOnHand: 32,
    quantityReserved: 10,
    quantityOnOrder: 50,
    safetyStock: 30,
    reorderPoint: 50,
    dailyDemand: 18,
    unitCost: 14500,
    unitPrice: 19800,
    holdingCostPerUnit: 450,
    supplierId: 'sup-505',
    supplierName: 'PowerTech Energy',
    leadTimeDays: 8,
    supplierReliability: 82,
    activePurchaseOrders: 1,
    riskLevel: 'HIGH',
    stockoutProbability: 86,
    estimatedDaysToStockout: 1,
    healthStatus: 'CRITICAL',
    aiReplenishment: {
      action: 'EXPEDITE',
      quantity: 50,
      recommendedSupplier: 'PowerTech Energy',
      expectedArrivalDays: 2,
      confidence: 94,
      reasoning: 'High risk of immediate stockout! Expedite air shipment to maintain battery pack delivery commitments.',
    },
  },
  {
    id: 'inv-702',
    productId: 'prod-702',
    productName: 'Microcontroller Board V3',
    sku: 'MCU-3030',
    category: 'Electronics',
    location: 'Warehouse A - Sec 3',
    quantityOnHand: 95,
    quantityReserved: 12,
    quantityOnOrder: 100,
    safetyStock: 60,
    reorderPoint: 110,
    dailyDemand: 30,
    unitCost: 2200,
    unitPrice: 3400,
    holdingCostPerUnit: 80,
    supplierId: 'sup-606',
    supplierName: 'Silicon Express',
    leadTimeDays: 6,
    supplierReliability: 91,
    activePurchaseOrders: 1,
    riskLevel: 'MEDIUM',
    stockoutProbability: 38,
    estimatedDaysToStockout: 3,
    healthStatus: 'LOW_STOCK',
  },
  {
    id: 'inv-803',
    productId: 'prod-803',
    productName: 'High-Precision Servo Actuator',
    sku: 'ACT-9011',
    category: 'Hardware',
    location: 'Warehouse B - Sec 4',
    quantityOnHand: 550,
    quantityReserved: 35,
    quantityOnOrder: 0,
    safetyStock: 100,
    reorderPoint: 180,
    dailyDemand: 22,
    unitCost: 7800,
    unitPrice: 11200,
    holdingCostPerUnit: 280,
    supplierId: 'sup-202',
    supplierName: 'Precision Motors Tech',
    leadTimeDays: 10,
    supplierReliability: 94,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 4,
    estimatedDaysToStockout: 25,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'inv-904',
    productId: 'prod-904',
    productName: 'Optical Encoder Module',
    sku: 'ENC-1022',
    category: 'Sensors',
    location: 'Warehouse C - Sec 2',
    quantityOnHand: 18,
    quantityReserved: 8,
    quantityOnOrder: 50,
    safetyStock: 25,
    reorderPoint: 40,
    dailyDemand: 12,
    unitCost: 1900,
    unitPrice: 2850,
    holdingCostPerUnit: 60,
    supplierId: 'sup-707',
    supplierName: 'OptoTech Systems',
    leadTimeDays: 7,
    supplierReliability: 85,
    activePurchaseOrders: 1,
    riskLevel: 'HIGH',
    stockoutProbability: 82,
    estimatedDaysToStockout: 1,
    healthStatus: 'CRITICAL',
  },
  {
    id: 'inv-1005',
    productId: 'prod-1005',
    productName: 'Step-Down Voltage Regulator',
    sku: 'REG-5055',
    category: 'Electronics',
    location: 'Warehouse A - Sec 1',
    quantityOnHand: 820,
    quantityReserved: 60,
    quantityOnOrder: 0,
    safetyStock: 150,
    reorderPoint: 300,
    dailyDemand: 45,
    unitCost: 850,
    unitPrice: 1400,
    holdingCostPerUnit: 30,
    supplierId: 'sup-303',
    supplierName: 'Apex Components',
    leadTimeDays: 5,
    supplierReliability: 97,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 1,
    estimatedDaysToStockout: 18,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'inv-1106',
    productId: 'prod-1106',
    productName: 'Heavy Duty Wiring Harness',
    sku: 'HAR-8821',
    category: 'Assemblies',
    location: 'Warehouse B - Sec 7',
    quantityOnHand: 140,
    quantityReserved: 20,
    quantityOnOrder: 150,
    safetyStock: 80,
    reorderPoint: 160,
    dailyDemand: 28,
    unitCost: 1600,
    unitPrice: 2600,
    holdingCostPerUnit: 55,
    supplierId: 'sup-808',
    supplierName: 'CableFlex Corp',
    leadTimeDays: 6,
    supplierReliability: 90,
    activePurchaseOrders: 1,
    riskLevel: 'MEDIUM',
    stockoutProbability: 40,
    estimatedDaysToStockout: 5,
    healthStatus: 'LOW_STOCK',
  },
  {
    id: 'inv-1207',
    productId: 'prod-1207',
    productName: 'Hydraulic Valve Assembly',
    sku: 'HVA-7740',
    category: 'Hardware',
    location: 'Warehouse B - Sec 9',
    quantityOnHand: 65,
    quantityReserved: 10,
    quantityOnOrder: 80,
    safetyStock: 40,
    reorderPoint: 80,
    dailyDemand: 10,
    unitCost: 11200,
    unitPrice: 16500,
    holdingCostPerUnit: 400,
    supplierId: 'sup-909',
    supplierName: 'Fluidic Engineering',
    leadTimeDays: 14,
    supplierReliability: 87,
    activePurchaseOrders: 1,
    riskLevel: 'MEDIUM',
    stockoutProbability: 48,
    estimatedDaysToStockout: 6,
    healthStatus: 'LOW_STOCK',
  },
  {
    id: 'inv-1308',
    productId: 'prod-1308',
    productName: 'Aluminum Chassis Mount',
    sku: 'CHA-1100',
    category: 'Assemblies',
    location: 'Warehouse C - Sec 1',
    quantityOnHand: 1200,
    quantityReserved: 150,
    quantityOnOrder: 0,
    safetyStock: 200,
    reorderPoint: 400,
    dailyDemand: 50,
    unitCost: 3200,
    unitPrice: 4800,
    holdingCostPerUnit: 110,
    supplierId: 'sup-303',
    supplierName: 'Apex Components',
    leadTimeDays: 5,
    supplierReliability: 97,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 0,
    estimatedDaysToStockout: 24,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'inv-1409',
    productId: 'prod-1409',
    productName: 'Brushless DC Fan 24V',
    sku: 'FAN-2401',
    category: 'Hardware',
    location: 'Warehouse A - Sec 8',
    quantityOnHand: 24,
    quantityReserved: 6,
    quantityOnOrder: 100,
    safetyStock: 30,
    reorderPoint: 60,
    dailyDemand: 20,
    unitCost: 650,
    unitPrice: 1100,
    holdingCostPerUnit: 25,
    supplierId: 'sup-1010',
    supplierName: 'AirCool Innovations',
    leadTimeDays: 5,
    supplierReliability: 83,
    activePurchaseOrders: 1,
    riskLevel: 'HIGH',
    stockoutProbability: 91,
    estimatedDaysToStockout: 1,
    healthStatus: 'CRITICAL',
  },
  {
    id: 'inv-1510',
    productId: 'prod-1510',
    productName: 'CAN-Bus Transceiver Chip',
    sku: 'CAN-6012',
    category: 'Electronics',
    location: 'Warehouse A - Sec 5',
    quantityOnHand: 175,
    quantityReserved: 25,
    quantityOnOrder: 200,
    safetyStock: 100,
    reorderPoint: 200,
    dailyDemand: 35,
    unitCost: 450,
    unitPrice: 790,
    holdingCostPerUnit: 20,
    supplierId: 'sup-101',
    supplierName: 'Local Supplier',
    leadTimeDays: 4,
    supplierReliability: 96,
    activePurchaseOrders: 1,
    riskLevel: 'MEDIUM',
    stockoutProbability: 42,
    estimatedDaysToStockout: 5,
    healthStatus: 'LOW_STOCK',
  },
  {
    id: 'inv-1611',
    productId: 'prod-1611',
    productName: 'Thermal Interface Paste',
    sku: 'TIM-0010',
    category: 'Chemicals',
    location: 'Warehouse C - Sec 6',
    quantityOnHand: 410,
    quantityReserved: 30,
    quantityOnOrder: 0,
    safetyStock: 80,
    reorderPoint: 150,
    dailyDemand: 16,
    unitCost: 350,
    unitPrice: 620,
    holdingCostPerUnit: 15,
    supplierId: 'sup-1111',
    supplierName: 'ChemTech Poly',
    leadTimeDays: 6,
    supplierReliability: 95,
    activePurchaseOrders: 0,
    riskLevel: 'LOW',
    stockoutProbability: 3,
    estimatedDaysToStockout: 25,
    healthStatus: 'HEALTHY',
  },
];

import { RecommendationService } from './recommendationService';

// Helper Data Access Functions (mocking future API layer)
export const getKPIMetrics = (): KPIMetric[] => MOCK_KPI_METRICS;
export const getInventoryHealth = (): InventoryHealthSummary => MOCK_INVENTORY_HEALTH;
export const getDemandVsInventoryData = (): DemandInventoryPoint[] => MOCK_DEMAND_INVENTORY_CHART;
export const getAIRecommendations = (): Recommendation[] => RecommendationService.getRecommendations();
export const getAlerts = (): Alert[] => MOCK_ALERTS;
export const getProducts = (): Product[] => MOCK_PRODUCTS;
export const getSuppliers = (): Supplier[] => MOCK_SUPPLIERS;
export const getSimulationResults = (): SimulationResult[] => MOCK_SIMULATION_RESULTS;
export const getActivities = (): ActivityItem[] => MOCK_ACTIVITIES;

export const getInventoryItems = (): InventoryItem[] => MOCK_INVENTORY_ITEMS;

export const getInventoryItemById = (id: string): InventoryItem | undefined => {
  return MOCK_INVENTORY_ITEMS.find((item) => item.id === id || item.productId === id);
};

export const filterInventoryItems = (
  query: string,
  statusFilter: 'ALL' | 'HEALTHY' | 'LOW_STOCK' | 'CRITICAL',
  categoryFilter?: string,
  supplierFilter?: string,
  riskFilter?: string
): InventoryItem[] => {
  return MOCK_INVENTORY_ITEMS.filter((item) => {
    // Search query matching product name, SKU, or category
    const q = query.trim().toLowerCase();
    if (q) {
      const matchName = item.productName.toLowerCase().includes(q);
      const matchSku = item.sku.toLowerCase().includes(q);
      const matchCat = item.category.toLowerCase().includes(q);
      if (!matchName && !matchSku && !matchCat) return false;
    }

    // Status chip filter
    if (statusFilter !== 'ALL' && item.healthStatus !== statusFilter) {
      return false;
    }

    // Category filter
    if (categoryFilter && categoryFilter !== 'ALL' && item.category !== categoryFilter) {
      return false;
    }

    // Supplier filter
    if (supplierFilter && supplierFilter !== 'ALL' && item.supplierName !== supplierFilter) {
      return false;
    }

    // Risk level filter
    if (riskFilter && riskFilter !== 'ALL' && item.riskLevel !== riskFilter) {
      return false;
    }

    return true;
  });
};
