"""
===================================================================================
DISCRETE CONSERVATIVE Q-LEARNING (CQL) PYTORCH MODEL & AGENT
===================================================================================

Implementation of Discrete Conservative Q-Learning (Kumar et al., 2020) for 
Offline Reinforcement Learning with State Standardization & Gradient Tracking.

Disclaimer & Data Documentation:
"This CQL model is trained offline on simulated behavioral experience (offline_cql_dataset.npz)
generated by SupplyChainEnv and seeded DemandHistory. It is not trained on real human decision logs."

Zero database mutations are performed during training or inference.
===================================================================================
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from typing import Dict, Any, Tuple, Optional


class DiscreteQNetwork(nn.Module):
    """PyTorch MLP Q-Network mapping 9-element state observation to 3 discrete action Q-values."""

    def __init__(self, state_dim: int = 9, action_dim: int = 3, hidden_dim: int = 128):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(state_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, action_dim),
        )

    def forward(self, state: torch.Tensor) -> torch.Tensor:
        return self.net(state)


class CQLAgent:
    """Discrete Conservative Q-Learning (CQL) Agent with State Standardization."""

    def __init__(
        self,
        state_dim: int = 9,
        action_dim: int = 3,
        hidden_dim: int = 128,
        lr: float = 3e-4,
        gamma: float = 0.99,
        tau: float = 0.005,
        cql_weight: float = 1.0,
        state_mean: Optional[np.ndarray] = None,
        state_std: Optional[np.ndarray] = None,
        device: str = "cpu",
    ):
        self.state_dim = state_dim
        self.action_dim = action_dim
        self.gamma = gamma
        self.tau = tau
        self.cql_weight = cql_weight
        self.device = torch.device(device)

        # Primary Q-Network and Target Q-Network
        self.q_net = DiscreteQNetwork(state_dim, action_dim, hidden_dim).to(self.device)
        self.target_q_net = DiscreteQNetwork(state_dim, action_dim, hidden_dim).to(self.device)

        # Synchronize target network weights
        self.target_q_net.load_state_dict(self.q_net.state_dict())
        self.target_q_net.eval()

        self.optimizer = optim.Adam(self.q_net.parameters(), lr=lr, weight_decay=1e-4)

        # State Normalization Statistics
        self.state_mean: Optional[np.ndarray] = None
        self.state_std: Optional[np.ndarray] = None
        self.state_mean_tensor: Optional[torch.Tensor] = None
        self.state_std_tensor: Optional[torch.Tensor] = None

        if state_mean is not None and state_std is not None:
            self.set_normalization(state_mean, state_std)

    def set_normalization(self, mean: np.ndarray, std: np.ndarray):
        """Set state mean and std for input standardization."""
        self.state_mean = np.array(mean, dtype=np.float32)
        safe_std = np.where(std < 1e-6, 1.0, std)
        self.state_std = np.array(safe_std, dtype=np.float32)

        self.state_mean_tensor = torch.FloatTensor(self.state_mean).to(self.device)
        self.state_std_tensor = torch.FloatTensor(self.state_std).to(self.device)

    def update(
        self,
        states_norm: torch.Tensor,
        actions: torch.Tensor,
        rewards_scaled: torch.Tensor,
        next_states_norm: torch.Tensor,
        dones: torch.Tensor,
    ) -> Dict[str, float]:
        """Perform a single CQL gradient update step.
        
        Loss = Bellman_MSE_Loss + cql_weight * LogSumExp_Conservative_Penalty
        """
        self.q_net.train()
        states_norm = states_norm.to(self.device)
        actions = actions.to(self.device).long()
        rewards_scaled = rewards_scaled.to(self.device).float()
        next_states_norm = next_states_norm.to(self.device)
        dones = dones.to(self.device).float()

        # 1. Calculate 1-step Target Q-value y = r_scaled + gamma * (1 - d) * max_a' Q_target(s'_norm, a')
        with torch.no_grad():
            next_q_values = self.target_q_net(next_states_norm)
            max_next_q, _ = torch.max(next_q_values, dim=1)
            target_y = rewards_scaled + self.gamma * (1.0 - dones) * max_next_q

        # 2. Evaluate current Q-values for dataset actions Q(s_norm, a_dataset)
        q_all = self.q_net(states_norm)  # shape (batch_size, action_dim)
        q_actions = q_all.gather(1, actions.unsqueeze(1)).squeeze(1)  # shape (batch_size,)

        # 3. Standard Bellman Mean Squared Error Loss
        bellman_loss = torch.nn.functional.mse_loss(q_actions, target_y)

        # 4. Discrete CQL Conservative Penalty: LogSumExp(Q(s_norm, a)) - Q(s_norm, a_dataset)
        cql_logsumexp = torch.logsumexp(q_all, dim=1)  # shape (batch_size,)
        cql_loss = torch.mean(cql_logsumexp - q_actions)

        # 5. Combined Total CQL Loss
        total_loss = bellman_loss + self.cql_weight * cql_loss

        # 6. Optimization step & Gradient Norm Tracking
        self.optimizer.zero_grad()
        total_loss.backward()

        # Calculate gradient norm before clipping
        total_norm = 0.0
        for p in self.q_net.parameters():
            if p.grad is not None:
                param_norm = p.grad.data.norm(2)
                total_norm += param_norm.item() ** 2
        grad_norm_before = total_norm ** 0.5

        # Clip gradient norm to 1.0
        torch.nn.utils.clip_grad_norm_(self.q_net.parameters(), max_norm=1.0)

        # Calculate gradient norm after clipping
        total_norm_after = 0.0
        for p in self.q_net.parameters():
            if p.grad is not None:
                param_norm = p.grad.data.norm(2)
                total_norm_after += param_norm.item() ** 2
        grad_norm_after = total_norm_after ** 0.5

        self.optimizer.step()

        # 7. Soft Target Network Update: theta_target <- tau * theta + (1 - tau) * theta_target
        for target_param, param in zip(self.target_q_net.parameters(), self.q_net.parameters()):
            target_param.data.copy_(self.tau * param.data + (1.0 - self.tau) * target_param.data)

        # Mean predicted Q-values per action for diagnostics
        q_means = torch.mean(q_all, dim=0).detach().cpu().numpy()

        return {
            "total_loss": total_loss.item(),
            "bellman_loss": bellman_loss.item(),
            "cql_loss": cql_loss.item(),
            "grad_norm_before": grad_norm_before,
            "grad_norm_after": grad_norm_after,
            "mean_q_noop": float(q_means[0]),
            "mean_q_order": float(q_means[1]),
            "mean_q_expedite": float(q_means[2]),
        }

    def select_action(self, obs: np.ndarray, deterministic: bool = True) -> int:
        """Select action using trained Q-Network with state standardization."""
        self.q_net.eval()
        with torch.no_grad():
            obs_array = np.array(obs, dtype=np.float32)
            if self.state_mean is not None and self.state_std is not None:
                obs_array = (obs_array - self.state_mean) / self.state_std

            state_tensor = torch.FloatTensor(obs_array).unsqueeze(0).to(self.device)
            q_values = self.q_net(state_tensor)
            action = int(torch.argmax(q_values, dim=1).item())
        return action

    def save_model(self, file_path: str):
        """Save PyTorch Q-Network weights and normalization statistics to disk."""
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        torch.save(
            {
                "q_net": self.q_net.state_dict(),
                "target_q_net": self.target_q_net.state_dict(),
                "state_dim": self.state_dim,
                "action_dim": self.action_dim,
                "cql_weight": self.cql_weight,
                "state_mean": self.state_mean,
                "state_std": self.state_std,
            },
            file_path,
        )

    def load_model(self, file_path: str):
        """Load PyTorch Q-Network weights and normalization statistics from disk."""
        checkpoint = torch.load(file_path, map_location=self.device, weights_only=False)
        self.q_net.load_state_dict(checkpoint["q_net"])
        self.target_q_net.load_state_dict(checkpoint["target_q_net"])
        if "state_mean" in checkpoint and checkpoint["state_mean"] is not None:
            self.set_normalization(checkpoint["state_mean"], checkpoint["state_std"])

        self.q_net.eval()
        self.target_q_net.eval()
