"""
===================================================================================
CQL (CONSERVATIVE Q-LEARNING) OFFLINE RL TRAINING & EVALUATION PIPELINE
===================================================================================

Trains a Discrete Conservative Q-Learning (CQL) agent using PyTorch on offline
experience dataset ('training/datasets/offline_cql_dataset.npz').

Evaluates policies (Always NOOP, Always ORDER, Always EXPEDITE, PPO RL Agent, CQL Offline Agent)
across ALL 20 products in SupplyChainEnv.

Disclaimer & Environment Notice:
"This evaluation measures policy performance on the simulated SupplyChainEnv environment
across all 20 products and does not represent real-world production performance."

"This CQL model is trained offline on simulated behavioral experience (offline_cql_dataset.npz)
generated by SupplyChainEnv and seeded DemandHistory. It is not trained on real human decision logs."

Zero database mutations are performed during training or evaluation.
===================================================================================
"""

import os
import sys
import argparse
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

sys.path.insert(0, os.path.abspath("."))

from database.db import SessionLocal
from database.models import InventoryRecord, Order, Product, Supplier
from services.rl_environment import SupplyChainEnv
from training.cql_model import CQLAgent
from stable_baselines3 import PPO


def evaluate_policy_across_all_products(
    db,
    policy_type: str,
    ppo_model: PPO = None,
    cql_agent: CQLAgent = None,
    num_products: int = 20,
    max_steps: int = 30,
) -> dict:
    """Evaluate a policy across ALL 20 products in SupplyChainEnv with reproducible seeds."""

    total_rewards = []
    total_profits = []
    service_levels = []
    stockout_units = []
    final_inventories = []
    per_product_details = []

    for p_id in range(1, num_products + 1):
        env = SupplyChainEnv(db=db, product_id=p_id, initial_inventory=50, max_steps=max_steps, fixed_order_quantity=50)
        obs, info = env.reset(seed=42 + p_id)
        done = False
        ep_reward = 0.0
        act_counts = {0: 0, 1: 0, 2: 0}

        while not done:
            if policy_type == "NOOP":
                action = 0
            elif policy_type == "ORDER":
                action = 1
            elif policy_type == "EXPEDITE":
                action = 2
            elif policy_type == "PPO":
                if ppo_model is None:
                    raise ValueError("PPO model is required for PPO evaluation")
                action, _ = ppo_model.predict(obs, deterministic=True)
                action = int(action)
            elif policy_type == "CQL":
                if cql_agent is None:
                    raise ValueError("CQL agent is required for CQL evaluation")
                action = cql_agent.select_action(obs, deterministic=True)
            else:
                raise ValueError(f"Unknown policy type {policy_type}")

            act_counts[action] += 1
            obs, reward, terminated, truncated, step_info = env.step(action)
            ep_reward += reward
            done = terminated or truncated

        total_rewards.append(ep_reward)
        total_profits.append(step_info["cumulative_profit"])
        service_levels.append(step_info["service_level"])
        stockout_units.append(step_info["stockout_quantity"])
        final_inventories.append(step_info["ending_inventory"])

        # Fetch supplier info for reporting
        sup = env.supplier
        per_product_details.append(
            {
                "product_id": p_id,
                "lead_time": sup.lead_time_days if sup else 0,
                "reliability": sup.reliability_score if sup else 0.0,
                "action_counts": act_counts,
                "reward": ep_reward,
                "profit": step_info["cumulative_profit"],
                "service_level": step_info["service_level"],
                "final_inventory": step_info["ending_inventory"],
            }
        )

    return {
        "avg_reward": float(np.mean(total_rewards)),
        "total_profit": float(np.mean(total_profits)),
        "service_level": float(np.mean(service_levels)),
        "avg_stockout": float(np.mean(stockout_units)),
        "final_inventory": float(np.mean(final_inventories)),
        "per_product": per_product_details,
    }


def print_cql_per_product_breakdown(cql_eval_metrics: dict):
    """Print detailed per-product CQL policy behavior breakdown."""
    print("=========================================================================================================")
    print("PER-PRODUCT CQL POLICY BEHAVIOR BREAKDOWN (ALL 20 PRODUCTS)")
    print("=========================================================================================================")
    print(f"{'ProdID':6s} | {'Lead Time':9s} | {'Reliability':11s} | {'CQL Actions (NOOP / ORDER / EXP)':34s} | {'Service Level (%)':17s} | {'Total Profit ($)':17s}")
    print("-" * 105)

    for item in cql_eval_metrics["per_product"]:
        p_id = item["product_id"]
        lt = item["lead_time"]
        rel = item["reliability"]
        acts = item["action_counts"]
        sl = item["service_level"]
        prof = item["profit"]

        act_str = f"NOOP: {acts[0]:2d} | ORDER: {acts[1]:2d} | EXP: {acts[2]:2d}"
        print(f"  {p_id:2d}   | {lt:4d} days  |    {rel:5.2f}    | {act_str:34s} |      {sl:6.2f}%       | ${prof:16,.2f}")

    print("=========================================================================================================\n")


def train_and_evaluate_cql(
    epochs: int = 30,
    batch_size: int = 256,
    cql_weight: float = 1.0,
    reward_scale: float = 1000.0,
    lr: float = 3e-4,
    eval_all_products: bool = True,
):
    print("==================================================================")
    print("CQL (CONSERVATIVE Q-LEARNING) FIXED OFFLINE RL PIPELINE")
    print("==================================================================\n")

    db = SessionLocal()

    # Verify initial DB state to guarantee zero mutations
    inv_before = [(r.id, r.quantity) for r in db.query(InventoryRecord).all()]
    orders_before = [(o.id, o.status) for o in db.query(Order).all()]
    print(f"Initial DB State: {len(inv_before)} InventoryRecords, {len(orders_before)} Orders.")

    # 1. Load Offline Dataset
    dataset_path = os.path.join("training", "datasets", "offline_cql_dataset.npz")
    if not os.path.exists(dataset_path):
        raise FileNotFoundError(f"Offline dataset not found at '{dataset_path}'. Please run generate_offline_dataset.py first.")

    print(f"Step 1: Loading offline dataset from '{dataset_path}'...")
    data = np.load(dataset_path)

    raw_states = data["states"]
    raw_next_states = data["next_states"]
    raw_rewards = data["rewards"]
    raw_actions = data["actions"]
    raw_dones = data["dones"]

    # 2. Compute State Feature Standardization Statistics (No Data Leakage)
    state_mean = np.mean(raw_states, axis=0, dtype=np.float32)
    state_std = np.std(raw_states, axis=0, dtype=np.float32)
    state_std = np.where(state_std < 1e-6, 1.0, state_std)

    print(f"Step 2: Computed State Normalization Statistics (Mean range: [{np.min(state_mean):.2f}..{np.max(state_mean):.2f}], Std range: [{np.min(state_std):.2f}..{np.max(state_std):.2f}]).")
    print(f"        Training-Only Reward Scaling applied: rewards / {reward_scale:.1f}.")

    # Normalize States & Scale Rewards for DataLoader
    states_norm = torch.FloatTensor((raw_states - state_mean) / state_std)
    next_states_norm = torch.FloatTensor((raw_next_states - state_mean) / state_std)
    actions_tensor = torch.LongTensor(raw_actions)
    rewards_scaled_tensor = torch.FloatTensor(raw_rewards / reward_scale)
    dones_tensor = torch.FloatTensor(raw_dones)

    dataset = TensorDataset(states_norm, actions_tensor, rewards_scaled_tensor, next_states_norm, dones_tensor)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    print(f"  - Loaded {len(dataset):,} transition tuples into DataLoader (Batch size: {batch_size}).")

    # 3. Instantiate CQL Agent with Normalization Parameters
    print("\nStep 3: Instantiating PyTorch CQL Agent with State Normalization...")
    agent = CQLAgent(
        state_dim=9,
        action_dim=3,
        hidden_dim=128,
        lr=lr,
        gamma=0.99,
        tau=0.005,
        cql_weight=cql_weight,
        state_mean=state_mean,
        state_std=state_std,
    )

    # 4. Train CQL Agent with Diagnostic Logging
    print(f"\nStep 4: Training CQL Agent for {epochs} epochs (Reward Scale: {reward_scale:.1f}, CQL Weight: {cql_weight:.2f})...")
    print("-" * 115)
    print(f"{'Epoch':7s} | {'Total Loss':10s} | {'Bellman MSE':11s} | {'CQL Penalty':11s} | {'GradNorm(Pre/Post)':18s} | {'Mean Q(NOOP)':12s} | {'Mean Q(ORD)':11s} | {'Mean Q(EXP)':11s}")
    print("-" * 115)

    for epoch in range(1, epochs + 1):
        tot_list, bel_list, cql_list = [], [], []
        gb_list, ga_list = [], []
        q0_list, q1_list, q2_list = [], [], []

        for b_states, b_actions, b_rewards, b_next_states, b_dones in loader:
            metrics = agent.update(b_states, b_actions, b_rewards, b_next_states, b_dones)
            tot_list.append(metrics["total_loss"])
            bel_list.append(metrics["bellman_loss"])
            cql_list.append(metrics["cql_loss"])
            gb_list.append(metrics["grad_norm_before"])
            ga_list.append(metrics["grad_norm_after"])
            q0_list.append(metrics["mean_q_noop"])
            q1_list.append(metrics["mean_q_order"])
            q2_list.append(metrics["mean_q_expedite"])

        if epoch == 1 or epoch % 5 == 0 or epoch == epochs:
            print(
                f"Epoch {epoch:2d}/{epochs} | "
                f"{np.mean(tot_list):10.2f} | "
                f"{np.mean(bel_list):11.2f} | "
                f"{np.mean(cql_list):11.2f} | "
                f"{np.mean(gb_list):7.2f} / {np.mean(ga_list):7.2f} | "
                f"{np.mean(q0_list):12.2f} | "
                f"{np.mean(q1_list):11.2f} | "
                f"{np.mean(q2_list):11.2f}"
            )

    print("-" * 115)

    # 5. Save Model Checkpoint
    save_path = os.path.join("training", "saved_models", "cql_supply_chain.pt")
    agent.save_model(save_path)
    print(f"\nStep 5: Saved trained CQL model & normalization params to '{os.path.abspath(save_path)}'.")

    # 6. Load Checkpoint to Verify Save/Load Cycle
    loaded_agent = CQLAgent(state_dim=9, action_dim=3, hidden_dim=128, cql_weight=cql_weight)
    loaded_agent.load_model(save_path)
    print("Step 6: Loaded trained CQL model & normalization params successfully from disk.")

    # 7. Load Trained PPO Model if Available
    ppo_model_path = os.path.join("training", "saved_models", "ppo_supply_chain.zip")
    ppo_model = None
    if os.path.exists(ppo_model_path):
        ppo_model = PPO.load(ppo_model_path)

    # 8. Evaluate All Policies Across ALL 20 Products
    print(f"\nStep 7: Evaluating All Policies across ALL 20 Products on SupplyChainEnv (30-day horizons, Unscaled Metrics)...")
    
    cql_eval_res = evaluate_policy_across_all_products(db, "CQL", cql_agent=loaded_agent)
    
    policies = {
        "Always NOOP": evaluate_policy_across_all_products(db, "NOOP"),
        "Always ORDER": evaluate_policy_across_all_products(db, "ORDER"),
        "Always EXPEDITE": evaluate_policy_across_all_products(db, "EXPEDITE"),
    }

    if ppo_model:
        policies["PPO RL Agent"] = evaluate_policy_across_all_products(db, "PPO", ppo_model=ppo_model)

    policies["Fixed CQL Agent"] = cql_eval_res

    # 9. Print Per-Product CQL Behavior Breakdown
    print_cql_per_product_breakdown(cql_eval_res)

    # 10. Render Global Multi-Product KPI Summary Table
    print("=========================================================================================================")
    print("MULTI-PRODUCT POLICY COMPARISON SUMMARY (ALL 20 PRODUCTS, 30-DAY EPISODES)")
    print("=========================================================================================================")
    print(f"{'Policy':18s} | {'Avg Episode Reward':19s} | {'Total Profit ($)':17s} | {'Service Level (%)':17s} | {'Avg Stockout':12s} | {'Final Inv':9s}")
    print("-" * 105)

    for pol_name, metrics in policies.items():
        print(
            f"{pol_name:18s} | "
            f"{metrics['avg_reward']:19,.2f} | "
            f"${metrics['total_profit']:16,.2f} | "
            f"{metrics['service_level']:16.2f}% | "
            f"{metrics['avg_stockout']:12.2f} | "
            f"{metrics['final_inventory']:<9.1f}"
        )
    print("=========================================================================================================\n")

    # 11. Verify 0 Database Mutations
    inv_after = [(r.id, r.quantity) for r in db.query(InventoryRecord).all()]
    orders_after = [(o.id, o.status) for o in db.query(Order).all()]
    db.close()

    assert inv_before == inv_after, "ERROR: InventoryRecord table was mutated!"
    assert orders_before == orders_after, "ERROR: Order table was mutated!"
    print("DATABASE ISOLATION VERIFIED: 100% Zero SQLite database mutations occurred during training & evaluation.\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train and Evaluate Fixed Discrete CQL Offline RL Model Across All Products")
    parser.add_argument("--epochs", type=int, default=30, help="Number of training epochs")
    parser.add_argument("--batch-size", type=int, default=256, help="Batch size for training")
    parser.add_argument("--cql-weight", type=float, default=1.0, help="CQL conservative loss weight alpha")
    parser.add_argument("--reward-scale", type=float, default=1000.0, help="Reward scaling factor for training")
    parser.add_argument("--lr", type=float, default=3e-4, help="Learning rate")
    args = parser.parse_args()

    train_and_evaluate_cql(
        epochs=args.epochs,
        batch_size=args.batch_size,
        cql_weight=args.cql_weight,
        reward_scale=args.reward_scale,
        lr=args.lr,
    )
